/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AClassdeclsFirstClassDecls extends PClassDecls
{
    private PClassDecls _classDecls_;
    private PClassDecl _classDecl_;

    public AClassdeclsFirstClassDecls()
    {
        // Constructor
    }

    public AClassdeclsFirstClassDecls(
        @SuppressWarnings("hiding") PClassDecls _classDecls_,
        @SuppressWarnings("hiding") PClassDecl _classDecl_)
    {
        // Constructor
        setClassDecls(_classDecls_);

        setClassDecl(_classDecl_);

    }

    @Override
    public Object clone()
    {
        return new AClassdeclsFirstClassDecls(
            cloneNode(this._classDecls_),
            cloneNode(this._classDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassdeclsFirstClassDecls(this);
    }

    public PClassDecls getClassDecls()
    {
        return this._classDecls_;
    }

    public void setClassDecls(PClassDecls node)
    {
        if(this._classDecls_ != null)
        {
            this._classDecls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classDecls_ = node;
    }

    public PClassDecl getClassDecl()
    {
        return this._classDecl_;
    }

    public void setClassDecl(PClassDecl node)
    {
        if(this._classDecl_ != null)
        {
            this._classDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classDecls_)
            + toString(this._classDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classDecls_ == child)
        {
            this._classDecls_ = null;
            return;
        }

        if(this._classDecl_ == child)
        {
            this._classDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classDecls_ == oldChild)
        {
            setClassDecls((PClassDecls) newChild);
            return;
        }

        if(this._classDecl_ == oldChild)
        {
            setClassDecl((PClassDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
