/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AClasshdrFirstClassHdr extends PClassHdr
{
    private TClazz _clazz_;
    private TId _id_;

    public AClasshdrFirstClassHdr()
    {
        // Constructor
    }

    public AClasshdrFirstClassHdr(
        @SuppressWarnings("hiding") TClazz _clazz_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setClazz(_clazz_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AClasshdrFirstClassHdr(
            cloneNode(this._clazz_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClasshdrFirstClassHdr(this);
    }

    public TClazz getClazz()
    {
        return this._clazz_;
    }

    public void setClazz(TClazz node)
    {
        if(this._clazz_ != null)
        {
            this._clazz_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._clazz_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._clazz_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._clazz_ == child)
        {
            this._clazz_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._clazz_ == oldChild)
        {
            setClazz((TClazz) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
