/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEfiveThreeExprUnaryOprt extends PExprUnaryOprt
{
    private TMinus _minus_;
    private PExprUnaryOprt _exprUnaryOprt_;

    public AEfiveThreeExprUnaryOprt()
    {
        // Constructor
    }

    public AEfiveThreeExprUnaryOprt(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PExprUnaryOprt _exprUnaryOprt_)
    {
        // Constructor
        setMinus(_minus_);

        setExprUnaryOprt(_exprUnaryOprt_);

    }

    @Override
    public Object clone()
    {
        return new AEfiveThreeExprUnaryOprt(
            cloneNode(this._minus_),
            cloneNode(this._exprUnaryOprt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEfiveThreeExprUnaryOprt(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PExprUnaryOprt getExprUnaryOprt()
    {
        return this._exprUnaryOprt_;
    }

    public void setExprUnaryOprt(PExprUnaryOprt node)
    {
        if(this._exprUnaryOprt_ != null)
        {
            this._exprUnaryOprt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprUnaryOprt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._exprUnaryOprt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._exprUnaryOprt_ == child)
        {
            this._exprUnaryOprt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._exprUnaryOprt_ == oldChild)
        {
            setExprUnaryOprt((PExprUnaryOprt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
