/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEfourTwoExprMulDiv extends PExprMulDiv
{
    private PExprMulDiv _exprMulDiv_;
    private TDiv _div_;
    private PExprUnaryOprt _exprUnaryOprt_;

    public AEfourTwoExprMulDiv()
    {
        // Constructor
    }

    public AEfourTwoExprMulDiv(
        @SuppressWarnings("hiding") PExprMulDiv _exprMulDiv_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PExprUnaryOprt _exprUnaryOprt_)
    {
        // Constructor
        setExprMulDiv(_exprMulDiv_);

        setDiv(_div_);

        setExprUnaryOprt(_exprUnaryOprt_);

    }

    @Override
    public Object clone()
    {
        return new AEfourTwoExprMulDiv(
            cloneNode(this._exprMulDiv_),
            cloneNode(this._div_),
            cloneNode(this._exprUnaryOprt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEfourTwoExprMulDiv(this);
    }

    public PExprMulDiv getExprMulDiv()
    {
        return this._exprMulDiv_;
    }

    public void setExprMulDiv(PExprMulDiv node)
    {
        if(this._exprMulDiv_ != null)
        {
            this._exprMulDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMulDiv_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PExprUnaryOprt getExprUnaryOprt()
    {
        return this._exprUnaryOprt_;
    }

    public void setExprUnaryOprt(PExprUnaryOprt node)
    {
        if(this._exprUnaryOprt_ != null)
        {
            this._exprUnaryOprt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprUnaryOprt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMulDiv_)
            + toString(this._div_)
            + toString(this._exprUnaryOprt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMulDiv_ == child)
        {
            this._exprMulDiv_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._exprUnaryOprt_ == child)
        {
            this._exprUnaryOprt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMulDiv_ == oldChild)
        {
            setExprMulDiv((PExprMulDiv) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._exprUnaryOprt_ == oldChild)
        {
            setExprUnaryOprt((PExprUnaryOprt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
