/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEthreeThreeExprAddSub extends PExprAddSub
{
    private PExprMulDiv _exprMulDiv_;

    public AEthreeThreeExprAddSub()
    {
        // Constructor
    }

    public AEthreeThreeExprAddSub(
        @SuppressWarnings("hiding") PExprMulDiv _exprMulDiv_)
    {
        // Constructor
        setExprMulDiv(_exprMulDiv_);

    }

    @Override
    public Object clone()
    {
        return new AEthreeThreeExprAddSub(
            cloneNode(this._exprMulDiv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEthreeThreeExprAddSub(this);
    }

    public PExprMulDiv getExprMulDiv()
    {
        return this._exprMulDiv_;
    }

    public void setExprMulDiv(PExprMulDiv node)
    {
        if(this._exprMulDiv_ != null)
        {
            this._exprMulDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMulDiv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMulDiv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMulDiv_ == child)
        {
            this._exprMulDiv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMulDiv_ == oldChild)
        {
            setExprMulDiv((PExprMulDiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
