/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEtwoThreeExprLogical extends PExprLogical
{
    private PExprLogical _ethreeOne_;
    private TLteq _lteq_;
    private PExprAddSub _ethreeTwo_;

    public AEtwoThreeExprLogical()
    {
        // Constructor
    }

    public AEtwoThreeExprLogical(
        @SuppressWarnings("hiding") PExprLogical _ethreeOne_,
        @SuppressWarnings("hiding") TLteq _lteq_,
        @SuppressWarnings("hiding") PExprAddSub _ethreeTwo_)
    {
        // Constructor
        setEthreeOne(_ethreeOne_);

        setLteq(_lteq_);

        setEthreeTwo(_ethreeTwo_);

    }

    @Override
    public Object clone()
    {
        return new AEtwoThreeExprLogical(
            cloneNode(this._ethreeOne_),
            cloneNode(this._lteq_),
            cloneNode(this._ethreeTwo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEtwoThreeExprLogical(this);
    }

    public PExprLogical getEthreeOne()
    {
        return this._ethreeOne_;
    }

    public void setEthreeOne(PExprLogical node)
    {
        if(this._ethreeOne_ != null)
        {
            this._ethreeOne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ethreeOne_ = node;
    }

    public TLteq getLteq()
    {
        return this._lteq_;
    }

    public void setLteq(TLteq node)
    {
        if(this._lteq_ != null)
        {
            this._lteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lteq_ = node;
    }

    public PExprAddSub getEthreeTwo()
    {
        return this._ethreeTwo_;
    }

    public void setEthreeTwo(PExprAddSub node)
    {
        if(this._ethreeTwo_ != null)
        {
            this._ethreeTwo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ethreeTwo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ethreeOne_)
            + toString(this._lteq_)
            + toString(this._ethreeTwo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ethreeOne_ == child)
        {
            this._ethreeOne_ = null;
            return;
        }

        if(this._lteq_ == child)
        {
            this._lteq_ = null;
            return;
        }

        if(this._ethreeTwo_ == child)
        {
            this._ethreeTwo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ethreeOne_ == oldChild)
        {
            setEthreeOne((PExprLogical) newChild);
            return;
        }

        if(this._lteq_ == oldChild)
        {
            setLteq((TLteq) newChild);
            return;
        }

        if(this._ethreeTwo_ == oldChild)
        {
            setEthreeTwo((PExprAddSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
