/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExprThreeExpr extends PExpr
{
    private PExprLogical _exprLogical_;

    public AExprThreeExpr()
    {
        // Constructor
    }

    public AExprThreeExpr(
        @SuppressWarnings("hiding") PExprLogical _exprLogical_)
    {
        // Constructor
        setExprLogical(_exprLogical_);

    }

    @Override
    public Object clone()
    {
        return new AExprThreeExpr(
            cloneNode(this._exprLogical_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprThreeExpr(this);
    }

    public PExprLogical getExprLogical()
    {
        return this._exprLogical_;
    }

    public void setExprLogical(PExprLogical node)
    {
        if(this._exprLogical_ != null)
        {
            this._exprLogical_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprLogical_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprLogical_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprLogical_ == child)
        {
            this._exprLogical_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprLogical_ == oldChild)
        {
            setExprLogical((PExprLogical) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
