/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFormalsFirstFormals extends PFormals
{
    private PFormal _formal_;

    public AFormalsFirstFormals()
    {
        // Constructor
    }

    public AFormalsFirstFormals(
        @SuppressWarnings("hiding") PFormal _formal_)
    {
        // Constructor
        setFormal(_formal_);

    }

    @Override
    public Object clone()
    {
        return new AFormalsFirstFormals(
            cloneNode(this._formal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormalsFirstFormals(this);
    }

    public PFormal getFormal()
    {
        return this._formal_;
    }

    public void setFormal(PFormal node)
    {
        if(this._formal_ != null)
        {
            this._formal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formal_ == child)
        {
            this._formal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formal_ == oldChild)
        {
            setFormal((PFormal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
