/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APrimaryFourPrimary extends PPrimary
{
    private TCharacterConstant _characterConstant_;

    public APrimaryFourPrimary()
    {
        // Constructor
    }

    public APrimaryFourPrimary(
        @SuppressWarnings("hiding") TCharacterConstant _characterConstant_)
    {
        // Constructor
        setCharacterConstant(_characterConstant_);

    }

    @Override
    public Object clone()
    {
        return new APrimaryFourPrimary(
            cloneNode(this._characterConstant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimaryFourPrimary(this);
    }

    public TCharacterConstant getCharacterConstant()
    {
        return this._characterConstant_;
    }

    public void setCharacterConstant(TCharacterConstant node)
    {
        if(this._characterConstant_ != null)
        {
            this._characterConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._characterConstant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._characterConstant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._characterConstant_ == child)
        {
            this._characterConstant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._characterConstant_ == oldChild)
        {
            setCharacterConstant((TCharacterConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
