/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStmtFirstStmt extends PStmt
{
    private PMif _mif_;

    public AStmtFirstStmt()
    {
        // Constructor
    }

    public AStmtFirstStmt(
        @SuppressWarnings("hiding") PMif _mif_)
    {
        // Constructor
        setMif(_mif_);

    }

    @Override
    public Object clone()
    {
        return new AStmtFirstStmt(
            cloneNode(this._mif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtFirstStmt(this);
    }

    public PMif getMif()
    {
        return this._mif_;
    }

    public void setMif(PMif node)
    {
        if(this._mif_ != null)
        {
            this._mif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mif_ == child)
        {
            this._mif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mif_ == oldChild)
        {
            setMif((PMif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
