/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUifSecondUif extends PUif
{
    private TIf _if_;
    private PCondition _condition_;
    private PMif _mif_;
    private TElse _else_;
    private PUif _uif_;

    public AUifSecondUif()
    {
        // Constructor
    }

    public AUifSecondUif(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") PMif _mif_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PUif _uif_)
    {
        // Constructor
        setIf(_if_);

        setCondition(_condition_);

        setMif(_mif_);

        setElse(_else_);

        setUif(_uif_);

    }

    @Override
    public Object clone()
    {
        return new AUifSecondUif(
            cloneNode(this._if_),
            cloneNode(this._condition_),
            cloneNode(this._mif_),
            cloneNode(this._else_),
            cloneNode(this._uif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUifSecondUif(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PMif getMif()
    {
        return this._mif_;
    }

    public void setMif(PMif node)
    {
        if(this._mif_ != null)
        {
            this._mif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mif_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PUif getUif()
    {
        return this._uif_;
    }

    public void setUif(PUif node)
    {
        if(this._uif_ != null)
        {
            this._uif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._condition_)
            + toString(this._mif_)
            + toString(this._else_)
            + toString(this._uif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._mif_ == child)
        {
            this._mif_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._uif_ == child)
        {
            this._uif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._mif_ == oldChild)
        {
            setMif((PMif) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._uif_ == oldChild)
        {
            setUif((PUif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
