/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TCaretEqual extends Token
{
    public TCaretEqual()
    {
        super.setText("^=");
    }

    public TCaretEqual(int line, int pos)
    {
        super.setText("^=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCaretEqual(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCaretEqual(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCaretEqual text.");
    }
}
