/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TModEqual extends Token
{
    public TModEqual()
    {
        super.setText("%=");
    }

    public TModEqual(int line, int pos)
    {
        super.setText("%=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TModEqual(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTModEqual(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TModEqual text.");
    }
}
