/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEfiveTwoExprUnaryOprt extends PExprUnaryOprt
{
    private TPlus _plus_;
    private PExprUnaryOprt _exprUnaryOprt_;

    public AEfiveTwoExprUnaryOprt()
    {
        // Constructor
    }

    public AEfiveTwoExprUnaryOprt(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PExprUnaryOprt _exprUnaryOprt_)
    {
        // Constructor
        setPlus(_plus_);

        setExprUnaryOprt(_exprUnaryOprt_);

    }

    @Override
    public Object clone()
    {
        return new AEfiveTwoExprUnaryOprt(
            cloneNode(this._plus_),
            cloneNode(this._exprUnaryOprt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEfiveTwoExprUnaryOprt(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PExprUnaryOprt getExprUnaryOprt()
    {
        return this._exprUnaryOprt_;
    }

    public void setExprUnaryOprt(PExprUnaryOprt node)
    {
        if(this._exprUnaryOprt_ != null)
        {
            this._exprUnaryOprt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprUnaryOprt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._exprUnaryOprt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._exprUnaryOprt_ == child)
        {
            this._exprUnaryOprt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._exprUnaryOprt_ == oldChild)
        {
            setExprUnaryOprt((PExprUnaryOprt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
