/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEtwoTwoExprLogical extends PExprLogical
{
    private PExprLogical _ethreeOne_;
    private TGt _gt_;
    private PExprAddSub _ethreeTwo_;

    public AEtwoTwoExprLogical()
    {
        // Constructor
    }

    public AEtwoTwoExprLogical(
        @SuppressWarnings("hiding") PExprLogical _ethreeOne_,
        @SuppressWarnings("hiding") TGt _gt_,
        @SuppressWarnings("hiding") PExprAddSub _ethreeTwo_)
    {
        // Constructor
        setEthreeOne(_ethreeOne_);

        setGt(_gt_);

        setEthreeTwo(_ethreeTwo_);

    }

    @Override
    public Object clone()
    {
        return new AEtwoTwoExprLogical(
            cloneNode(this._ethreeOne_),
            cloneNode(this._gt_),
            cloneNode(this._ethreeTwo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEtwoTwoExprLogical(this);
    }

    public PExprLogical getEthreeOne()
    {
        return this._ethreeOne_;
    }

    public void setEthreeOne(PExprLogical node)
    {
        if(this._ethreeOne_ != null)
        {
            this._ethreeOne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ethreeOne_ = node;
    }

    public TGt getGt()
    {
        return this._gt_;
    }

    public void setGt(TGt node)
    {
        if(this._gt_ != null)
        {
            this._gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gt_ = node;
    }

    public PExprAddSub getEthreeTwo()
    {
        return this._ethreeTwo_;
    }

    public void setEthreeTwo(PExprAddSub node)
    {
        if(this._ethreeTwo_ != null)
        {
            this._ethreeTwo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ethreeTwo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ethreeOne_)
            + toString(this._gt_)
            + toString(this._ethreeTwo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ethreeOne_ == child)
        {
            this._ethreeOne_ = null;
            return;
        }

        if(this._gt_ == child)
        {
            this._gt_ = null;
            return;
        }

        if(this._ethreeTwo_ == child)
        {
            this._ethreeTwo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ethreeOne_ == oldChild)
        {
            setEthreeOne((PExprLogical) newChild);
            return;
        }

        if(this._gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

        if(this._ethreeTwo_ == oldChild)
        {
            setEthreeTwo((PExprAddSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
