/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEtwoSevenExprLogical extends PExprLogical
{
    private PExprAddSub _exprAddSub_;

    public AEtwoSevenExprLogical()
    {
        // Constructor
    }

    public AEtwoSevenExprLogical(
        @SuppressWarnings("hiding") PExprAddSub _exprAddSub_)
    {
        // Constructor
        setExprAddSub(_exprAddSub_);

    }

    @Override
    public Object clone()
    {
        return new AEtwoSevenExprLogical(
            cloneNode(this._exprAddSub_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEtwoSevenExprLogical(this);
    }

    public PExprAddSub getExprAddSub()
    {
        return this._exprAddSub_;
    }

    public void setExprAddSub(PExprAddSub node)
    {
        if(this._exprAddSub_ != null)
        {
            this._exprAddSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprAddSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprAddSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprAddSub_ == child)
        {
            this._exprAddSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprAddSub_ == oldChild)
        {
            setExprAddSub((PExprAddSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
