/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMemberdeclsFirstMemberDecls extends PMemberDecls
{
    private PMemberDecls _memberDecls_;
    private PMember _member_;

    public AMemberdeclsFirstMemberDecls()
    {
        // Constructor
    }

    public AMemberdeclsFirstMemberDecls(
        @SuppressWarnings("hiding") PMemberDecls _memberDecls_,
        @SuppressWarnings("hiding") PMember _member_)
    {
        // Constructor
        setMemberDecls(_memberDecls_);

        setMember(_member_);

    }

    @Override
    public Object clone()
    {
        return new AMemberdeclsFirstMemberDecls(
            cloneNode(this._memberDecls_),
            cloneNode(this._member_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMemberdeclsFirstMemberDecls(this);
    }

    public PMemberDecls getMemberDecls()
    {
        return this._memberDecls_;
    }

    public void setMemberDecls(PMemberDecls node)
    {
        if(this._memberDecls_ != null)
        {
            this._memberDecls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._memberDecls_ = node;
    }

    public PMember getMember()
    {
        return this._member_;
    }

    public void setMember(PMember node)
    {
        if(this._member_ != null)
        {
            this._member_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._member_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._memberDecls_)
            + toString(this._member_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._memberDecls_ == child)
        {
            this._memberDecls_ = null;
            return;
        }

        if(this._member_ == child)
        {
            this._member_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._memberDecls_ == oldChild)
        {
            setMemberDecls((PMemberDecls) newChild);
            return;
        }

        if(this._member_ == oldChild)
        {
            setMember((PMember) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
