/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMifFirstMif extends PMif
{
    private TIf _if_;
    private PCondition _condition_;
    private PMif _mifOne_;
    private TElse _else_;
    private PMif _mifTwo_;

    public AMifFirstMif()
    {
        // Constructor
    }

    public AMifFirstMif(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") PMif _mifOne_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PMif _mifTwo_)
    {
        // Constructor
        setIf(_if_);

        setCondition(_condition_);

        setMifOne(_mifOne_);

        setElse(_else_);

        setMifTwo(_mifTwo_);

    }

    @Override
    public Object clone()
    {
        return new AMifFirstMif(
            cloneNode(this._if_),
            cloneNode(this._condition_),
            cloneNode(this._mifOne_),
            cloneNode(this._else_),
            cloneNode(this._mifTwo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMifFirstMif(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PMif getMifOne()
    {
        return this._mifOne_;
    }

    public void setMifOne(PMif node)
    {
        if(this._mifOne_ != null)
        {
            this._mifOne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mifOne_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PMif getMifTwo()
    {
        return this._mifTwo_;
    }

    public void setMifTwo(PMif node)
    {
        if(this._mifTwo_ != null)
        {
            this._mifTwo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mifTwo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._condition_)
            + toString(this._mifOne_)
            + toString(this._else_)
            + toString(this._mifTwo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._mifOne_ == child)
        {
            this._mifOne_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._mifTwo_ == child)
        {
            this._mifTwo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._mifOne_ == oldChild)
        {
            setMifOne((PMif) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._mifTwo_ == oldChild)
        {
            setMifTwo((PMif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
