/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APrimaryThreePrimary extends PPrimary
{
    private TIntegerConstant _integerConstant_;

    public APrimaryThreePrimary()
    {
        // Constructor
    }

    public APrimaryThreePrimary(
        @SuppressWarnings("hiding") TIntegerConstant _integerConstant_)
    {
        // Constructor
        setIntegerConstant(_integerConstant_);

    }

    @Override
    public Object clone()
    {
        return new APrimaryThreePrimary(
            cloneNode(this._integerConstant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimaryThreePrimary(this);
    }

    public TIntegerConstant getIntegerConstant()
    {
        return this._integerConstant_;
    }

    public void setIntegerConstant(TIntegerConstant node)
    {
        if(this._integerConstant_ != null)
        {
            this._integerConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integerConstant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._integerConstant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._integerConstant_ == child)
        {
            this._integerConstant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._integerConstant_ == oldChild)
        {
            setIntegerConstant((TIntegerConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
