/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStmtSecondStmt extends PStmt
{
    private PUif _uif_;

    public AStmtSecondStmt()
    {
        // Constructor
    }

    public AStmtSecondStmt(
        @SuppressWarnings("hiding") PUif _uif_)
    {
        // Constructor
        setUif(_uif_);

    }

    @Override
    public Object clone()
    {
        return new AStmtSecondStmt(
            cloneNode(this._uif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtSecondStmt(this);
    }

    public PUif getUif()
    {
        return this._uif_;
    }

    public void setUif(PUif node)
    {
        if(this._uif_ != null)
        {
            this._uif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._uif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._uif_ == child)
        {
            this._uif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._uif_ == oldChild)
        {
            setUif((PUif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
